package com.baidu.navisdk.ui.cruise.view;

import com.baidu.navisdk.C4048R;

public class BCruiserR {
    public static final int[] BlindBendTypeIResID = new int[]{C4048R.drawable.nsdk_drawable_rg_cruise_blindbend_left, C4048R.drawable.nsdk_drawable_rg_cruise_blindbend_left, C4048R.drawable.nsdk_drawable_rg_cruise_blindbend_right, C4048R.drawable.nsdk_drawable_rg_cruise_blindbend_reverse, C4048R.drawable.nsdk_drawable_rg_cruise_blindbend_continuous};
    public static final int[] CAMERA_ICON_ID = new int[]{C4048R.drawable.nsdk_drawable_rg_cruise_joint_right, C4048R.drawable.nsdk_drawable_rg_cruise_tunnel, C4048R.drawable.nsdk_drawable_rg_cruise_bridge, C4048R.drawable.nsdk_drawable_rg_cruise_railway_managed, C4048R.drawable.nsdk_drawable_rg_cruise_blindbend_left, C4048R.drawable.nsdk_drawable_rg_cruise_blindslope, C4048R.drawable.nsdk_drawable_rg_cruise_rockfall_left, C4048R.drawable.nsdk_drawable_rg_cruise_accident, C4048R.drawable.nsdk_drawable_rg_cruise_limitcamera, C4048R.drawable.nsdk_drawable_rg_cruise_peccanrycamera, C4048R.drawable.nsdk_drawable_rg_cruise_peccanrycamera, C4048R.drawable.nsdk_drawable_rg_cruise_limitcamera, C4048R.drawable.nsdk_drawable_rg_cruise_children, C4048R.drawable.nsdk_drawable_rg_cruise_uneven, C4048R.drawable.nsdk_drawable_rg_cruise_narrow_both, C4048R.drawable.nsdk_drawable_rg_cruise_viliage, C4048R.drawable.nsdk_drawable_rg_cruise_slip, C4048R.drawable.nsdk_drawable_rg_cruise_overtakeforbidden, C4048R.drawable.nsdk_drawable_rg_cruise_honk, C4048R.drawable.nsdk_drawable_rg_cruise_hillsidedangerous, C4048R.drawable.nsdk_drawable_rg_cruise_narrowbridge, C4048R.drawable.nsdk_drawable_rg_cruise_crosswind, C4048R.drawable.nsdk_drawable_rg_cruise_underwater, C4048R.drawable.nsdk_drawable_rg_cruise_lowspeed, C4048R.drawable.nsdk_drawable_rg_cruise_zippass};
    public static final int[] JointTypeIResID = new int[]{C4048R.drawable.nsdk_drawable_rg_cruise_joint_right, C4048R.drawable.nsdk_drawable_rg_cruise_joint_left, C4048R.drawable.nsdk_drawable_rg_cruise_joint_right, C4048R.drawable.nsdk_drawable_rg_cruise_joint_right};
    public static final int[] NarrowTypeIResID = new int[]{C4048R.drawable.nsdk_drawable_rg_cruise_narrow_both, C4048R.drawable.nsdk_drawable_rg_cruise_narrow_left, C4048R.drawable.nsdk_drawable_rg_cruise_narrow_right, C4048R.drawable.nsdk_drawable_rg_cruise_narrow_both};
    public static final int[] RailwayTypeIResID = new int[]{C4048R.drawable.nsdk_drawable_rg_cruise_railway_managed, C4048R.drawable.nsdk_drawable_rg_cruise_railway_managed, C4048R.drawable.nsdk_drawable_rg_cruise_railway_unmanaged};
    public static final int[] RockFallTypeIResID = new int[]{C4048R.drawable.nsdk_drawable_rg_cruise_rockfall_left, C4048R.drawable.nsdk_drawable_rg_cruise_rockfall_left, C4048R.drawable.nsdk_drawable_rg_cruise_rockfall_right};
    public static final int[] SlopTypeIResID = new int[]{C4048R.drawable.nsdk_drawable_rg_cruise_blindslope, C4048R.drawable.nsdk_drawable_rg_cruise_blindslope_up, C4048R.drawable.nsdk_drawable_rg_cruise_blindslope_down, C4048R.drawable.nsdk_drawable_rg_cruise_blindslope};
}
