// Generated by the protocol buffer compiler.  DO NOT EDIT!

package me.objectyan.screensharing.protobuf;

public final class CarlifeConnectExceptionProto {
  private CarlifeConnectExceptionProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class CarlifeConnectException extends
      com.google.protobuf.GeneratedMessage {
    // Use CarlifeConnectException.newBuilder() to construct.
    private CarlifeConnectException() {}
    
    private static final CarlifeConnectException defaultInstance = new CarlifeConnectException();
    public static CarlifeConnectException getDefaultInstance() {
      return defaultInstance;
    }
    
    public CarlifeConnectException getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return me.objectyan.screensharing.protobuf.CarlifeConnectExceptionProto.internal_static_com_baidu_carlife_protobuf_CarlifeConnectException_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return me.objectyan.screensharing.protobuf.CarlifeConnectExceptionProto.internal_static_com_baidu_carlife_protobuf_CarlifeConnectException_fieldAccessorTable;
    }
    
    // required int32 exceptionType = 1;
    public static final int EXCEPTIONTYPE_FIELD_NUMBER = 1;
    private boolean hasExceptionType;
    private int exceptionType_ = 0;
    public boolean hasExceptionType() { return hasExceptionType; }
    public int getExceptionType() { return exceptionType_; }
    
    public final boolean isInitialized() {
      if (!hasExceptionType) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasExceptionType()) {
        output.writeInt32(1, getExceptionType());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasExceptionType()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getExceptionType());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static me.objectyan.screensharing.protobuf.CarlifeConnectExceptionProto.CarlifeConnectException parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static me.objectyan.screensharing.protobuf.CarlifeConnectExceptionProto.CarlifeConnectException parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static me.objectyan.screensharing.protobuf.CarlifeConnectExceptionProto.CarlifeConnectException parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static me.objectyan.screensharing.protobuf.CarlifeConnectExceptionProto.CarlifeConnectException parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static me.objectyan.screensharing.protobuf.CarlifeConnectExceptionProto.CarlifeConnectException parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static me.objectyan.screensharing.protobuf.CarlifeConnectExceptionProto.CarlifeConnectException parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static me.objectyan.screensharing.protobuf.CarlifeConnectExceptionProto.CarlifeConnectException parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static me.objectyan.screensharing.protobuf.CarlifeConnectExceptionProto.CarlifeConnectException parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static me.objectyan.screensharing.protobuf.CarlifeConnectExceptionProto.CarlifeConnectException parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static me.objectyan.screensharing.protobuf.CarlifeConnectExceptionProto.CarlifeConnectException parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(me.objectyan.screensharing.protobuf.CarlifeConnectExceptionProto.CarlifeConnectException prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private me.objectyan.screensharing.protobuf.CarlifeConnectExceptionProto.CarlifeConnectException result;
      
      // Construct using me.objectyan.screensharing.protobuf.CarlifeConnectExceptionProto.CarlifeConnectException.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new me.objectyan.screensharing.protobuf.CarlifeConnectExceptionProto.CarlifeConnectException();
        return builder;
      }
      
      protected me.objectyan.screensharing.protobuf.CarlifeConnectExceptionProto.CarlifeConnectException internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new me.objectyan.screensharing.protobuf.CarlifeConnectExceptionProto.CarlifeConnectException();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return me.objectyan.screensharing.protobuf.CarlifeConnectExceptionProto.CarlifeConnectException.getDescriptor();
      }
      
      public me.objectyan.screensharing.protobuf.CarlifeConnectExceptionProto.CarlifeConnectException getDefaultInstanceForType() {
        return me.objectyan.screensharing.protobuf.CarlifeConnectExceptionProto.CarlifeConnectException.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public me.objectyan.screensharing.protobuf.CarlifeConnectExceptionProto.CarlifeConnectException build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private me.objectyan.screensharing.protobuf.CarlifeConnectExceptionProto.CarlifeConnectException buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public me.objectyan.screensharing.protobuf.CarlifeConnectExceptionProto.CarlifeConnectException buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        me.objectyan.screensharing.protobuf.CarlifeConnectExceptionProto.CarlifeConnectException returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof me.objectyan.screensharing.protobuf.CarlifeConnectExceptionProto.CarlifeConnectException) {
          return mergeFrom((me.objectyan.screensharing.protobuf.CarlifeConnectExceptionProto.CarlifeConnectException)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(me.objectyan.screensharing.protobuf.CarlifeConnectExceptionProto.CarlifeConnectException other) {
        if (other == me.objectyan.screensharing.protobuf.CarlifeConnectExceptionProto.CarlifeConnectException.getDefaultInstance()) return this;
        if (other.hasExceptionType()) {
          setExceptionType(other.getExceptionType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setExceptionType(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // required int32 exceptionType = 1;
      public boolean hasExceptionType() {
        return result.hasExceptionType();
      }
      public int getExceptionType() {
        return result.getExceptionType();
      }
      public Builder setExceptionType(int value) {
        result.hasExceptionType = true;
        result.exceptionType_ = value;
        return this;
      }
      public Builder clearExceptionType() {
        result.hasExceptionType = false;
        result.exceptionType_ = 0;
        return this;
      }
    }
    
    static {
      me.objectyan.screensharing.protobuf.CarlifeConnectExceptionProto.getDescriptor();
    }
    
    static {
      me.objectyan.screensharing.protobuf.CarlifeConnectExceptionProto.internalForceInit();
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_baidu_carlife_protobuf_CarlifeConnectException_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_baidu_carlife_protobuf_CarlifeConnectException_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\"CarlifeConnectExceptionProto.proto\022\032co" +
      "m.baidu.carlife.protobuf\"0\n\027CarlifeConne" +
      "ctException\022\025\n\rexceptionType\030\001 \002(\005"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_baidu_carlife_protobuf_CarlifeConnectException_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_baidu_carlife_protobuf_CarlifeConnectException_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_baidu_carlife_protobuf_CarlifeConnectException_descriptor,
              new String[] { "ExceptionType", },
              me.objectyan.screensharing.protobuf.CarlifeConnectExceptionProto.CarlifeConnectException.class,
              me.objectyan.screensharing.protobuf.CarlifeConnectExceptionProto.CarlifeConnectException.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
}
