// Generated by the protocol buffer compiler.  DO NOT EDIT!

package me.objectyan.screensharing.protobuf;

public final class CarlifeBTStartIdentifyReqProto {
  private CarlifeBTStartIdentifyReqProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class CarlifeBTStartIdentifyReq extends
      com.google.protobuf.GeneratedMessage {
    // Use CarlifeBTStartIdentifyReq.newBuilder() to construct.
    private CarlifeBTStartIdentifyReq() {}
    
    private static final CarlifeBTStartIdentifyReq defaultInstance = new CarlifeBTStartIdentifyReq();
    public static CarlifeBTStartIdentifyReq getDefaultInstance() {
      return defaultInstance;
    }
    
    public CarlifeBTStartIdentifyReq getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return me.objectyan.screensharing.protobuf.CarlifeBTStartIdentifyReqProto.internal_static_com_baidu_carlife_protobuf_CarlifeBTStartIdentifyReq_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return me.objectyan.screensharing.protobuf.CarlifeBTStartIdentifyReqProto.internal_static_com_baidu_carlife_protobuf_CarlifeBTStartIdentifyReq_fieldAccessorTable;
    }
    
    // required string address = 1;
    public static final int ADDRESS_FIELD_NUMBER = 1;
    private boolean hasAddress;
    private String address_ = "";
    public boolean hasAddress() { return hasAddress; }
    public String getAddress() { return address_; }

    public final boolean isInitialized() {
      if (!hasAddress) return false;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasAddress()) {
        output.writeString(1, getAddress());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (hasAddress()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getAddress());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static me.objectyan.screensharing.protobuf.CarlifeBTStartIdentifyReqProto.CarlifeBTStartIdentifyReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static me.objectyan.screensharing.protobuf.CarlifeBTStartIdentifyReqProto.CarlifeBTStartIdentifyReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static me.objectyan.screensharing.protobuf.CarlifeBTStartIdentifyReqProto.CarlifeBTStartIdentifyReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static me.objectyan.screensharing.protobuf.CarlifeBTStartIdentifyReqProto.CarlifeBTStartIdentifyReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static me.objectyan.screensharing.protobuf.CarlifeBTStartIdentifyReqProto.CarlifeBTStartIdentifyReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static me.objectyan.screensharing.protobuf.CarlifeBTStartIdentifyReqProto.CarlifeBTStartIdentifyReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static me.objectyan.screensharing.protobuf.CarlifeBTStartIdentifyReqProto.CarlifeBTStartIdentifyReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static me.objectyan.screensharing.protobuf.CarlifeBTStartIdentifyReqProto.CarlifeBTStartIdentifyReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static me.objectyan.screensharing.protobuf.CarlifeBTStartIdentifyReqProto.CarlifeBTStartIdentifyReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static me.objectyan.screensharing.protobuf.CarlifeBTStartIdentifyReqProto.CarlifeBTStartIdentifyReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(me.objectyan.screensharing.protobuf.CarlifeBTStartIdentifyReqProto.CarlifeBTStartIdentifyReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private me.objectyan.screensharing.protobuf.CarlifeBTStartIdentifyReqProto.CarlifeBTStartIdentifyReq result;

      // Construct using me.objectyan.screensharing.protobuf.CarlifeBTStartIdentifyReqProto.CarlifeBTStartIdentifyReq.newBuilder()
      private Builder() {}

      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new me.objectyan.screensharing.protobuf.CarlifeBTStartIdentifyReqProto.CarlifeBTStartIdentifyReq();
        return builder;
      }

      protected me.objectyan.screensharing.protobuf.CarlifeBTStartIdentifyReqProto.CarlifeBTStartIdentifyReq internalGetResult() {
        return result;
      }

      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new me.objectyan.screensharing.protobuf.CarlifeBTStartIdentifyReqProto.CarlifeBTStartIdentifyReq();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(result);
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return me.objectyan.screensharing.protobuf.CarlifeBTStartIdentifyReqProto.CarlifeBTStartIdentifyReq.getDescriptor();
      }

      public me.objectyan.screensharing.protobuf.CarlifeBTStartIdentifyReqProto.CarlifeBTStartIdentifyReq getDefaultInstanceForType() {
        return me.objectyan.screensharing.protobuf.CarlifeBTStartIdentifyReqProto.CarlifeBTStartIdentifyReq.getDefaultInstance();
      }

      public boolean isInitialized() {
        return result.isInitialized();
      }
      public me.objectyan.screensharing.protobuf.CarlifeBTStartIdentifyReqProto.CarlifeBTStartIdentifyReq build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }

      private me.objectyan.screensharing.protobuf.CarlifeBTStartIdentifyReqProto.CarlifeBTStartIdentifyReq buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }

      public me.objectyan.screensharing.protobuf.CarlifeBTStartIdentifyReqProto.CarlifeBTStartIdentifyReq buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        me.objectyan.screensharing.protobuf.CarlifeBTStartIdentifyReqProto.CarlifeBTStartIdentifyReq returnMe = result;
        result = null;
        return returnMe;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof me.objectyan.screensharing.protobuf.CarlifeBTStartIdentifyReqProto.CarlifeBTStartIdentifyReq) {
          return mergeFrom((me.objectyan.screensharing.protobuf.CarlifeBTStartIdentifyReqProto.CarlifeBTStartIdentifyReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(me.objectyan.screensharing.protobuf.CarlifeBTStartIdentifyReqProto.CarlifeBTStartIdentifyReq other) {
        if (other == me.objectyan.screensharing.protobuf.CarlifeBTStartIdentifyReqProto.CarlifeBTStartIdentifyReq.getDefaultInstance()) return this;
        if (other.hasAddress()) {
          setAddress(other.getAddress());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setAddress(input.readString());
              break;
            }
          }
        }
      }


      // required string address = 1;
      public boolean hasAddress() {
        return result.hasAddress();
      }
      public String getAddress() {
        return result.getAddress();
      }
      public Builder setAddress(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasAddress = true;
        result.address_ = value;
        return this;
      }
      public Builder clearAddress() {
        result.hasAddress = false;
        result.address_ = getDefaultInstance().getAddress();
        return this;
      }
    }

    static {
      me.objectyan.screensharing.protobuf.CarlifeBTStartIdentifyReqProto.getDescriptor();
    }

    static {
      me.objectyan.screensharing.protobuf.CarlifeBTStartIdentifyReqProto.internalForceInit();
    }
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_baidu_carlife_protobuf_CarlifeBTStartIdentifyReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_baidu_carlife_protobuf_CarlifeBTStartIdentifyReq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n$CarlifeBTStartIdentifyReqProto.proto\022\032" +
      "me.objectyan.screensharing.protobuf\",\n\031CarlifeBTS" +
      "tartIdentifyReq\022\017\n\007address\030\001 \002(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_baidu_carlife_protobuf_CarlifeBTStartIdentifyReq_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_baidu_carlife_protobuf_CarlifeBTStartIdentifyReq_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_baidu_carlife_protobuf_CarlifeBTStartIdentifyReq_descriptor,
              new String[] { "Address", },
              me.objectyan.screensharing.protobuf.CarlifeBTStartIdentifyReqProto.CarlifeBTStartIdentifyReq.class,
              me.objectyan.screensharing.protobuf.CarlifeBTStartIdentifyReqProto.CarlifeBTStartIdentifyReq.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
}
