// Generated by the protocol buffer compiler.  DO NOT EDIT!

package me.objectyan.screensharing.protobuf;

public final class CarlifeMediaInfoListProto {
  private CarlifeMediaInfoListProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class CarlifeMediaInfoList extends
      com.google.protobuf.GeneratedMessage {
    // Use CarlifeMediaInfoList.newBuilder() to construct.
    private CarlifeMediaInfoList() {}
    
    private static final CarlifeMediaInfoList defaultInstance = new CarlifeMediaInfoList();
    public static CarlifeMediaInfoList getDefaultInstance() {
      return defaultInstance;
    }
    
    public CarlifeMediaInfoList getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return me.objectyan.screensharing.protobuf.CarlifeMediaInfoListProto.internal_static_com_baidu_carlife_protobuf_CarlifeMediaInfoList_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return me.objectyan.screensharing.protobuf.CarlifeMediaInfoListProto.internal_static_com_baidu_carlife_protobuf_CarlifeMediaInfoList_fieldAccessorTable;
    }
    
    // required int32 cnt = 1;
    public static final int CNT_FIELD_NUMBER = 1;
    private boolean hasCnt;
    private int cnt_ = 0;
    public boolean hasCnt() { return hasCnt; }
    public int getCnt() { return cnt_; }
    
    // repeated .me.objectyan.screensharing.protobuf.CarlifeMediaInfo mediaInfo = 2;
    public static final int MEDIAINFO_FIELD_NUMBER = 2;
    private java.util.List<me.objectyan.screensharing.protobuf.CarlifeMediaInfoProto.CarlifeMediaInfo> mediaInfo_ =
      java.util.Collections.emptyList();
    public java.util.List<me.objectyan.screensharing.protobuf.CarlifeMediaInfoProto.CarlifeMediaInfo> getMediaInfoList() {
      return mediaInfo_;
    }
    public int getMediaInfoCount() { return mediaInfo_.size(); }
    public me.objectyan.screensharing.protobuf.CarlifeMediaInfoProto.CarlifeMediaInfo getMediaInfo(int index) {
      return mediaInfo_.get(index);
    }
    
    public final boolean isInitialized() {
      if (!hasCnt) return false;
      for (me.objectyan.screensharing.protobuf.CarlifeMediaInfoProto.CarlifeMediaInfo element : getMediaInfoList()) {
        if (!element.isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasCnt()) {
        output.writeInt32(1, getCnt());
      }
      for (me.objectyan.screensharing.protobuf.CarlifeMediaInfoProto.CarlifeMediaInfo element : getMediaInfoList()) {
        output.writeMessage(2, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasCnt()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getCnt());
      }
      for (me.objectyan.screensharing.protobuf.CarlifeMediaInfoProto.CarlifeMediaInfo element : getMediaInfoList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, element);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static me.objectyan.screensharing.protobuf.CarlifeMediaInfoListProto.CarlifeMediaInfoList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static me.objectyan.screensharing.protobuf.CarlifeMediaInfoListProto.CarlifeMediaInfoList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static me.objectyan.screensharing.protobuf.CarlifeMediaInfoListProto.CarlifeMediaInfoList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static me.objectyan.screensharing.protobuf.CarlifeMediaInfoListProto.CarlifeMediaInfoList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static me.objectyan.screensharing.protobuf.CarlifeMediaInfoListProto.CarlifeMediaInfoList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static me.objectyan.screensharing.protobuf.CarlifeMediaInfoListProto.CarlifeMediaInfoList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static me.objectyan.screensharing.protobuf.CarlifeMediaInfoListProto.CarlifeMediaInfoList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static me.objectyan.screensharing.protobuf.CarlifeMediaInfoListProto.CarlifeMediaInfoList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static me.objectyan.screensharing.protobuf.CarlifeMediaInfoListProto.CarlifeMediaInfoList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static me.objectyan.screensharing.protobuf.CarlifeMediaInfoListProto.CarlifeMediaInfoList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(me.objectyan.screensharing.protobuf.CarlifeMediaInfoListProto.CarlifeMediaInfoList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private me.objectyan.screensharing.protobuf.CarlifeMediaInfoListProto.CarlifeMediaInfoList result;
      
      // Construct using me.objectyan.screensharing.protobuf.CarlifeMediaInfoListProto.CarlifeMediaInfoList.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new me.objectyan.screensharing.protobuf.CarlifeMediaInfoListProto.CarlifeMediaInfoList();
        return builder;
      }
      
      protected me.objectyan.screensharing.protobuf.CarlifeMediaInfoListProto.CarlifeMediaInfoList internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new me.objectyan.screensharing.protobuf.CarlifeMediaInfoListProto.CarlifeMediaInfoList();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return me.objectyan.screensharing.protobuf.CarlifeMediaInfoListProto.CarlifeMediaInfoList.getDescriptor();
      }
      
      public me.objectyan.screensharing.protobuf.CarlifeMediaInfoListProto.CarlifeMediaInfoList getDefaultInstanceForType() {
        return me.objectyan.screensharing.protobuf.CarlifeMediaInfoListProto.CarlifeMediaInfoList.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public me.objectyan.screensharing.protobuf.CarlifeMediaInfoListProto.CarlifeMediaInfoList build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private me.objectyan.screensharing.protobuf.CarlifeMediaInfoListProto.CarlifeMediaInfoList buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public me.objectyan.screensharing.protobuf.CarlifeMediaInfoListProto.CarlifeMediaInfoList buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.mediaInfo_ != java.util.Collections.EMPTY_LIST) {
          result.mediaInfo_ =
            java.util.Collections.unmodifiableList(result.mediaInfo_);
        }
        me.objectyan.screensharing.protobuf.CarlifeMediaInfoListProto.CarlifeMediaInfoList returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof me.objectyan.screensharing.protobuf.CarlifeMediaInfoListProto.CarlifeMediaInfoList) {
          return mergeFrom((me.objectyan.screensharing.protobuf.CarlifeMediaInfoListProto.CarlifeMediaInfoList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(me.objectyan.screensharing.protobuf.CarlifeMediaInfoListProto.CarlifeMediaInfoList other) {
        if (other == me.objectyan.screensharing.protobuf.CarlifeMediaInfoListProto.CarlifeMediaInfoList.getDefaultInstance()) return this;
        if (other.hasCnt()) {
          setCnt(other.getCnt());
        }
        if (!other.mediaInfo_.isEmpty()) {
          if (result.mediaInfo_.isEmpty()) {
            result.mediaInfo_ = new java.util.ArrayList<me.objectyan.screensharing.protobuf.CarlifeMediaInfoProto.CarlifeMediaInfo>();
          }
          result.mediaInfo_.addAll(other.mediaInfo_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setCnt(input.readInt32());
              break;
            }
            case 18: {
              me.objectyan.screensharing.protobuf.CarlifeMediaInfoProto.CarlifeMediaInfo.Builder subBuilder = me.objectyan.screensharing.protobuf.CarlifeMediaInfoProto.CarlifeMediaInfo.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addMediaInfo(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // required int32 cnt = 1;
      public boolean hasCnt() {
        return result.hasCnt();
      }
      public int getCnt() {
        return result.getCnt();
      }
      public Builder setCnt(int value) {
        result.hasCnt = true;
        result.cnt_ = value;
        return this;
      }
      public Builder clearCnt() {
        result.hasCnt = false;
        result.cnt_ = 0;
        return this;
      }
      
      // repeated .me.objectyan.screensharing.protobuf.CarlifeMediaInfo mediaInfo = 2;
      public java.util.List<me.objectyan.screensharing.protobuf.CarlifeMediaInfoProto.CarlifeMediaInfo> getMediaInfoList() {
        return java.util.Collections.unmodifiableList(result.mediaInfo_);
      }
      public int getMediaInfoCount() {
        return result.getMediaInfoCount();
      }
      public me.objectyan.screensharing.protobuf.CarlifeMediaInfoProto.CarlifeMediaInfo getMediaInfo(int index) {
        return result.getMediaInfo(index);
      }
      public Builder setMediaInfo(int index, me.objectyan.screensharing.protobuf.CarlifeMediaInfoProto.CarlifeMediaInfo value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.mediaInfo_.set(index, value);
        return this;
      }
      public Builder setMediaInfo(int index, me.objectyan.screensharing.protobuf.CarlifeMediaInfoProto.CarlifeMediaInfo.Builder builderForValue) {
        result.mediaInfo_.set(index, builderForValue.build());
        return this;
      }
      public Builder addMediaInfo(me.objectyan.screensharing.protobuf.CarlifeMediaInfoProto.CarlifeMediaInfo value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.mediaInfo_.isEmpty()) {
          result.mediaInfo_ = new java.util.ArrayList<me.objectyan.screensharing.protobuf.CarlifeMediaInfoProto.CarlifeMediaInfo>();
        }
        result.mediaInfo_.add(value);
        return this;
      }
      public Builder addMediaInfo(me.objectyan.screensharing.protobuf.CarlifeMediaInfoProto.CarlifeMediaInfo.Builder builderForValue) {
        if (result.mediaInfo_.isEmpty()) {
          result.mediaInfo_ = new java.util.ArrayList<me.objectyan.screensharing.protobuf.CarlifeMediaInfoProto.CarlifeMediaInfo>();
        }
        result.mediaInfo_.add(builderForValue.build());
        return this;
      }
      public Builder addAllMediaInfo(
          Iterable<? extends me.objectyan.screensharing.protobuf.CarlifeMediaInfoProto.CarlifeMediaInfo> values) {
        if (result.mediaInfo_.isEmpty()) {
          result.mediaInfo_ = new java.util.ArrayList<me.objectyan.screensharing.protobuf.CarlifeMediaInfoProto.CarlifeMediaInfo>();
        }
        super.addAll(values, result.mediaInfo_);
        return this;
      }
      public Builder clearMediaInfo() {
        result.mediaInfo_ = java.util.Collections.emptyList();
        return this;
      }
    }

    static {
      me.objectyan.screensharing.protobuf.CarlifeMediaInfoListProto.getDescriptor();
    }

    static {
      me.objectyan.screensharing.protobuf.CarlifeMediaInfoListProto.internalForceInit();
    }
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_baidu_carlife_protobuf_CarlifeMediaInfoList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_baidu_carlife_protobuf_CarlifeMediaInfoList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\037CarlifeMediaInfoListProto.proto\022\032com.b" +
      "aidu.carlife.protobuf\032\033CarlifeMediaInfoP" +
      "roto.proto\"d\n\024CarlifeMediaInfoList\022\013\n\003cn" +
      "t\030\001 \002(\005\022?\n\tmediaInfo\030\002 \003(\0132,.com.baidu.c" +
      "arlife.protobuf.CarlifeMediaInfo"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_baidu_carlife_protobuf_CarlifeMediaInfoList_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_baidu_carlife_protobuf_CarlifeMediaInfoList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_baidu_carlife_protobuf_CarlifeMediaInfoList_descriptor,
              new String[] { "Cnt", "MediaInfo", },
              me.objectyan.screensharing.protobuf.CarlifeMediaInfoListProto.CarlifeMediaInfoList.class,
              me.objectyan.screensharing.protobuf.CarlifeMediaInfoListProto.CarlifeMediaInfoList.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          me.objectyan.screensharing.protobuf.CarlifeMediaInfoProto.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
}
