// Generated by the protocol buffer compiler.  DO NOT EDIT!

package me.objectyan.screensharing.protobuf;

public final class CarlifeBTHfpIndicationProto {
  private CarlifeBTHfpIndicationProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class CarlifeBTHfpIndication extends
      com.google.protobuf.GeneratedMessage {
    // Use CarlifeBTHfpIndication.newBuilder() to construct.
    private CarlifeBTHfpIndication() {}
    
    private static final CarlifeBTHfpIndication defaultInstance = new CarlifeBTHfpIndication();
    public static CarlifeBTHfpIndication getDefaultInstance() {
      return defaultInstance;
    }
    
    public CarlifeBTHfpIndication getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return me.objectyan.screensharing.protobuf.CarlifeBTHfpIndicationProto.internal_static_com_baidu_carlife_protobuf_CarlifeBTHfpIndication_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return me.objectyan.screensharing.protobuf.CarlifeBTHfpIndicationProto.internal_static_com_baidu_carlife_protobuf_CarlifeBTHfpIndication_fieldAccessorTable;
    }
    
    // required int32 state = 1;
    public static final int STATE_FIELD_NUMBER = 1;
    private boolean hasState;
    private int state_ = 0;
    public boolean hasState() { return hasState; }
    public int getState() { return state_; }
    
    // optional string phoneNum = 2;
    public static final int PHONENUM_FIELD_NUMBER = 2;
    private boolean hasPhoneNum;
    private String phoneNum_ = "";
    public boolean hasPhoneNum() { return hasPhoneNum; }
    public String getPhoneNum() { return phoneNum_; }

    // optional string phoneName = 3;
    public static final int PHONENAME_FIELD_NUMBER = 3;
    private boolean hasPhoneName;
    private String phoneName_ = "";
    public boolean hasPhoneName() { return hasPhoneName; }
    public String getPhoneName() { return phoneName_; }

    // optional string address = 4;
    public static final int ADDRESS_FIELD_NUMBER = 4;
    private boolean hasAddress;
    private String address_ = "";
    public boolean hasAddress() { return hasAddress; }
    public String getAddress() { return address_; }

    public final boolean isInitialized() {
      if (!hasState) return false;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasState()) {
        output.writeInt32(1, getState());
      }
      if (hasPhoneNum()) {
        output.writeString(2, getPhoneNum());
      }
      if (hasPhoneName()) {
        output.writeString(3, getPhoneName());
      }
      if (hasAddress()) {
        output.writeString(4, getAddress());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (hasState()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getState());
      }
      if (hasPhoneNum()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getPhoneNum());
      }
      if (hasPhoneName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getPhoneName());
      }
      if (hasAddress()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getAddress());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static me.objectyan.screensharing.protobuf.CarlifeBTHfpIndicationProto.CarlifeBTHfpIndication parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static me.objectyan.screensharing.protobuf.CarlifeBTHfpIndicationProto.CarlifeBTHfpIndication parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static me.objectyan.screensharing.protobuf.CarlifeBTHfpIndicationProto.CarlifeBTHfpIndication parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static me.objectyan.screensharing.protobuf.CarlifeBTHfpIndicationProto.CarlifeBTHfpIndication parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static me.objectyan.screensharing.protobuf.CarlifeBTHfpIndicationProto.CarlifeBTHfpIndication parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static me.objectyan.screensharing.protobuf.CarlifeBTHfpIndicationProto.CarlifeBTHfpIndication parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static me.objectyan.screensharing.protobuf.CarlifeBTHfpIndicationProto.CarlifeBTHfpIndication parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static me.objectyan.screensharing.protobuf.CarlifeBTHfpIndicationProto.CarlifeBTHfpIndication parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static me.objectyan.screensharing.protobuf.CarlifeBTHfpIndicationProto.CarlifeBTHfpIndication parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static me.objectyan.screensharing.protobuf.CarlifeBTHfpIndicationProto.CarlifeBTHfpIndication parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(me.objectyan.screensharing.protobuf.CarlifeBTHfpIndicationProto.CarlifeBTHfpIndication prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private me.objectyan.screensharing.protobuf.CarlifeBTHfpIndicationProto.CarlifeBTHfpIndication result;

      // Construct using me.objectyan.screensharing.protobuf.CarlifeBTHfpIndicationProto.CarlifeBTHfpIndication.newBuilder()
      private Builder() {}

      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new me.objectyan.screensharing.protobuf.CarlifeBTHfpIndicationProto.CarlifeBTHfpIndication();
        return builder;
      }

      protected me.objectyan.screensharing.protobuf.CarlifeBTHfpIndicationProto.CarlifeBTHfpIndication internalGetResult() {
        return result;
      }

      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new me.objectyan.screensharing.protobuf.CarlifeBTHfpIndicationProto.CarlifeBTHfpIndication();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(result);
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return me.objectyan.screensharing.protobuf.CarlifeBTHfpIndicationProto.CarlifeBTHfpIndication.getDescriptor();
      }

      public me.objectyan.screensharing.protobuf.CarlifeBTHfpIndicationProto.CarlifeBTHfpIndication getDefaultInstanceForType() {
        return me.objectyan.screensharing.protobuf.CarlifeBTHfpIndicationProto.CarlifeBTHfpIndication.getDefaultInstance();
      }

      public boolean isInitialized() {
        return result.isInitialized();
      }
      public me.objectyan.screensharing.protobuf.CarlifeBTHfpIndicationProto.CarlifeBTHfpIndication build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }

      private me.objectyan.screensharing.protobuf.CarlifeBTHfpIndicationProto.CarlifeBTHfpIndication buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }

      public me.objectyan.screensharing.protobuf.CarlifeBTHfpIndicationProto.CarlifeBTHfpIndication buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        me.objectyan.screensharing.protobuf.CarlifeBTHfpIndicationProto.CarlifeBTHfpIndication returnMe = result;
        result = null;
        return returnMe;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof me.objectyan.screensharing.protobuf.CarlifeBTHfpIndicationProto.CarlifeBTHfpIndication) {
          return mergeFrom((me.objectyan.screensharing.protobuf.CarlifeBTHfpIndicationProto.CarlifeBTHfpIndication)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(me.objectyan.screensharing.protobuf.CarlifeBTHfpIndicationProto.CarlifeBTHfpIndication other) {
        if (other == me.objectyan.screensharing.protobuf.CarlifeBTHfpIndicationProto.CarlifeBTHfpIndication.getDefaultInstance()) return this;
        if (other.hasState()) {
          setState(other.getState());
        }
        if (other.hasPhoneNum()) {
          setPhoneNum(other.getPhoneNum());
        }
        if (other.hasPhoneName()) {
          setPhoneName(other.getPhoneName());
        }
        if (other.hasAddress()) {
          setAddress(other.getAddress());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setState(input.readInt32());
              break;
            }
            case 18: {
              setPhoneNum(input.readString());
              break;
            }
            case 26: {
              setPhoneName(input.readString());
              break;
            }
            case 34: {
              setAddress(input.readString());
              break;
            }
          }
        }
      }


      // required int32 state = 1;
      public boolean hasState() {
        return result.hasState();
      }
      public int getState() {
        return result.getState();
      }
      public Builder setState(int value) {
        result.hasState = true;
        result.state_ = value;
        return this;
      }
      public Builder clearState() {
        result.hasState = false;
        result.state_ = 0;
        return this;
      }

      // optional string phoneNum = 2;
      public boolean hasPhoneNum() {
        return result.hasPhoneNum();
      }
      public String getPhoneNum() {
        return result.getPhoneNum();
      }
      public Builder setPhoneNum(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasPhoneNum = true;
        result.phoneNum_ = value;
        return this;
      }
      public Builder clearPhoneNum() {
        result.hasPhoneNum = false;
        result.phoneNum_ = getDefaultInstance().getPhoneNum();
        return this;
      }

      // optional string phoneName = 3;
      public boolean hasPhoneName() {
        return result.hasPhoneName();
      }
      public String getPhoneName() {
        return result.getPhoneName();
      }
      public Builder setPhoneName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasPhoneName = true;
        result.phoneName_ = value;
        return this;
      }
      public Builder clearPhoneName() {
        result.hasPhoneName = false;
        result.phoneName_ = getDefaultInstance().getPhoneName();
        return this;
      }

      // optional string address = 4;
      public boolean hasAddress() {
        return result.hasAddress();
      }
      public String getAddress() {
        return result.getAddress();
      }
      public Builder setAddress(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasAddress = true;
        result.address_ = value;
        return this;
      }
      public Builder clearAddress() {
        result.hasAddress = false;
        result.address_ = getDefaultInstance().getAddress();
        return this;
      }
    }

    static {
      me.objectyan.screensharing.protobuf.CarlifeBTHfpIndicationProto.getDescriptor();
    }

    static {
      me.objectyan.screensharing.protobuf.CarlifeBTHfpIndicationProto.internalForceInit();
    }
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_baidu_carlife_protobuf_CarlifeBTHfpIndication_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_baidu_carlife_protobuf_CarlifeBTHfpIndication_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n!CarlifeBTHfpIndicationProto.proto\022\032com" +
      ".baidu.carlife.protobuf\"]\n\026CarlifeBTHfpI" +
      "ndication\022\r\n\005state\030\001 \002(\005\022\020\n\010phoneNum\030\002 \001" +
      "(\t\022\021\n\tphoneName\030\003 \001(\t\022\017\n\007address\030\004 \001(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_baidu_carlife_protobuf_CarlifeBTHfpIndication_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_baidu_carlife_protobuf_CarlifeBTHfpIndication_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_baidu_carlife_protobuf_CarlifeBTHfpIndication_descriptor,
              new String[] { "State", "PhoneNum", "PhoneName", "Address", },
              me.objectyan.screensharing.protobuf.CarlifeBTHfpIndicationProto.CarlifeBTHfpIndication.class,
              me.objectyan.screensharing.protobuf.CarlifeBTHfpIndicationProto.CarlifeBTHfpIndication.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
}
