// Generated by the protocol buffer compiler.  DO NOT EDIT!

package me.objectyan.screensharing.protobuf;

public final class CarlifeVideoFrameRateProto {
  private CarlifeVideoFrameRateProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class CarlifeVideoFrameRate extends
      com.google.protobuf.GeneratedMessage {
    // Use CarlifeVideoFrameRate.newBuilder() to construct.
    private CarlifeVideoFrameRate() {}
    
    private static final CarlifeVideoFrameRate defaultInstance = new CarlifeVideoFrameRate();
    public static CarlifeVideoFrameRate getDefaultInstance() {
      return defaultInstance;
    }
    
    public CarlifeVideoFrameRate getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return me.objectyan.screensharing.protobuf.CarlifeVideoFrameRateProto.internal_static_com_baidu_carlife_protobuf_CarlifeVideoFrameRate_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return me.objectyan.screensharing.protobuf.CarlifeVideoFrameRateProto.internal_static_com_baidu_carlife_protobuf_CarlifeVideoFrameRate_fieldAccessorTable;
    }
    
    // required int32 frameRate = 1;
    public static final int FRAMERATE_FIELD_NUMBER = 1;
    private boolean hasFrameRate;
    private int frameRate_ = 0;
    public boolean hasFrameRate() { return hasFrameRate; }
    public int getFrameRate() { return frameRate_; }
    
    public final boolean isInitialized() {
      if (!hasFrameRate) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasFrameRate()) {
        output.writeInt32(1, getFrameRate());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasFrameRate()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getFrameRate());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static me.objectyan.screensharing.protobuf.CarlifeVideoFrameRateProto.CarlifeVideoFrameRate parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static me.objectyan.screensharing.protobuf.CarlifeVideoFrameRateProto.CarlifeVideoFrameRate parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static me.objectyan.screensharing.protobuf.CarlifeVideoFrameRateProto.CarlifeVideoFrameRate parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static me.objectyan.screensharing.protobuf.CarlifeVideoFrameRateProto.CarlifeVideoFrameRate parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static me.objectyan.screensharing.protobuf.CarlifeVideoFrameRateProto.CarlifeVideoFrameRate parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static me.objectyan.screensharing.protobuf.CarlifeVideoFrameRateProto.CarlifeVideoFrameRate parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static me.objectyan.screensharing.protobuf.CarlifeVideoFrameRateProto.CarlifeVideoFrameRate parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static me.objectyan.screensharing.protobuf.CarlifeVideoFrameRateProto.CarlifeVideoFrameRate parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static me.objectyan.screensharing.protobuf.CarlifeVideoFrameRateProto.CarlifeVideoFrameRate parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static me.objectyan.screensharing.protobuf.CarlifeVideoFrameRateProto.CarlifeVideoFrameRate parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(me.objectyan.screensharing.protobuf.CarlifeVideoFrameRateProto.CarlifeVideoFrameRate prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private me.objectyan.screensharing.protobuf.CarlifeVideoFrameRateProto.CarlifeVideoFrameRate result;
      
      // Construct using me.objectyan.screensharing.protobuf.CarlifeVideoFrameRateProto.CarlifeVideoFrameRate.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new me.objectyan.screensharing.protobuf.CarlifeVideoFrameRateProto.CarlifeVideoFrameRate();
        return builder;
      }
      
      protected me.objectyan.screensharing.protobuf.CarlifeVideoFrameRateProto.CarlifeVideoFrameRate internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new me.objectyan.screensharing.protobuf.CarlifeVideoFrameRateProto.CarlifeVideoFrameRate();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return me.objectyan.screensharing.protobuf.CarlifeVideoFrameRateProto.CarlifeVideoFrameRate.getDescriptor();
      }
      
      public me.objectyan.screensharing.protobuf.CarlifeVideoFrameRateProto.CarlifeVideoFrameRate getDefaultInstanceForType() {
        return me.objectyan.screensharing.protobuf.CarlifeVideoFrameRateProto.CarlifeVideoFrameRate.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public me.objectyan.screensharing.protobuf.CarlifeVideoFrameRateProto.CarlifeVideoFrameRate build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private me.objectyan.screensharing.protobuf.CarlifeVideoFrameRateProto.CarlifeVideoFrameRate buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public me.objectyan.screensharing.protobuf.CarlifeVideoFrameRateProto.CarlifeVideoFrameRate buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        me.objectyan.screensharing.protobuf.CarlifeVideoFrameRateProto.CarlifeVideoFrameRate returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof me.objectyan.screensharing.protobuf.CarlifeVideoFrameRateProto.CarlifeVideoFrameRate) {
          return mergeFrom((me.objectyan.screensharing.protobuf.CarlifeVideoFrameRateProto.CarlifeVideoFrameRate)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(me.objectyan.screensharing.protobuf.CarlifeVideoFrameRateProto.CarlifeVideoFrameRate other) {
        if (other == me.objectyan.screensharing.protobuf.CarlifeVideoFrameRateProto.CarlifeVideoFrameRate.getDefaultInstance()) return this;
        if (other.hasFrameRate()) {
          setFrameRate(other.getFrameRate());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setFrameRate(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // required int32 frameRate = 1;
      public boolean hasFrameRate() {
        return result.hasFrameRate();
      }
      public int getFrameRate() {
        return result.getFrameRate();
      }
      public Builder setFrameRate(int value) {
        result.hasFrameRate = true;
        result.frameRate_ = value;
        return this;
      }
      public Builder clearFrameRate() {
        result.hasFrameRate = false;
        result.frameRate_ = 0;
        return this;
      }
    }
    
    static {
      me.objectyan.screensharing.protobuf.CarlifeVideoFrameRateProto.getDescriptor();
    }
    
    static {
      me.objectyan.screensharing.protobuf.CarlifeVideoFrameRateProto.internalForceInit();
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_baidu_carlife_protobuf_CarlifeVideoFrameRate_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_baidu_carlife_protobuf_CarlifeVideoFrameRate_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n CarlifeVideoFrameRateProto.proto\022\032com." +
      "baidu.carlife.protobuf\"*\n\025CarlifeVideoFr" +
      "ameRate\022\021\n\tframeRate\030\001 \002(\005"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_baidu_carlife_protobuf_CarlifeVideoFrameRate_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_baidu_carlife_protobuf_CarlifeVideoFrameRate_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_baidu_carlife_protobuf_CarlifeVideoFrameRate_descriptor,
              new String[] { "FrameRate", },
              me.objectyan.screensharing.protobuf.CarlifeVideoFrameRateProto.CarlifeVideoFrameRate.class,
              me.objectyan.screensharing.protobuf.CarlifeVideoFrameRateProto.CarlifeVideoFrameRate.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
}
