// Generated by the protocol buffer compiler.  DO NOT EDIT!

package me.objectyan.screensharing.protobuf;

public final class CarlifeContactsProto {
  private CarlifeContactsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class CarlifeContacts extends
      com.google.protobuf.GeneratedMessage {
    // Use CarlifeContacts.newBuilder() to construct.
    private CarlifeContacts() {}
    
    private static final CarlifeContacts defaultInstance = new CarlifeContacts();
    public static CarlifeContacts getDefaultInstance() {
      return defaultInstance;
    }
    
    public CarlifeContacts getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return me.objectyan.screensharing.protobuf.CarlifeContactsProto.internal_static_com_baidu_carlife_protobuf_CarlifeContacts_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return me.objectyan.screensharing.protobuf.CarlifeContactsProto.internal_static_com_baidu_carlife_protobuf_CarlifeContacts_fieldAccessorTable;
    }
    
    // required int32 cid = 1;
    public static final int CID_FIELD_NUMBER = 1;
    private boolean hasCid;
    private int cid_ = 0;
    public boolean hasCid() { return hasCid; }
    public int getCid() { return cid_; }
    
    // required string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private boolean hasName;
    private String name_ = "";
    public boolean hasName() { return hasName; }
    public String getName() { return name_; }

    // required string number = 3;
    public static final int NUMBER_FIELD_NUMBER = 3;
    private boolean hasNumber;
    private String number_ = "";
    public boolean hasNumber() { return hasNumber; }
    public String getNumber() { return number_; }

    public final boolean isInitialized() {
      if (!hasCid) return false;
      if (!hasName) return false;
      if (!hasNumber) return false;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasCid()) {
        output.writeInt32(1, getCid());
      }
      if (hasName()) {
        output.writeString(2, getName());
      }
      if (hasNumber()) {
        output.writeString(3, getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (hasCid()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getCid());
      }
      if (hasName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getName());
      }
      if (hasNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static me.objectyan.screensharing.protobuf.CarlifeContactsProto.CarlifeContacts parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static me.objectyan.screensharing.protobuf.CarlifeContactsProto.CarlifeContacts parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static me.objectyan.screensharing.protobuf.CarlifeContactsProto.CarlifeContacts parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static me.objectyan.screensharing.protobuf.CarlifeContactsProto.CarlifeContacts parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static me.objectyan.screensharing.protobuf.CarlifeContactsProto.CarlifeContacts parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static me.objectyan.screensharing.protobuf.CarlifeContactsProto.CarlifeContacts parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static me.objectyan.screensharing.protobuf.CarlifeContactsProto.CarlifeContacts parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static me.objectyan.screensharing.protobuf.CarlifeContactsProto.CarlifeContacts parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static me.objectyan.screensharing.protobuf.CarlifeContactsProto.CarlifeContacts parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static me.objectyan.screensharing.protobuf.CarlifeContactsProto.CarlifeContacts parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(me.objectyan.screensharing.protobuf.CarlifeContactsProto.CarlifeContacts prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private me.objectyan.screensharing.protobuf.CarlifeContactsProto.CarlifeContacts result;

      // Construct using me.objectyan.screensharing.protobuf.CarlifeContactsProto.CarlifeContacts.newBuilder()
      private Builder() {}

      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new me.objectyan.screensharing.protobuf.CarlifeContactsProto.CarlifeContacts();
        return builder;
      }

      protected me.objectyan.screensharing.protobuf.CarlifeContactsProto.CarlifeContacts internalGetResult() {
        return result;
      }

      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new me.objectyan.screensharing.protobuf.CarlifeContactsProto.CarlifeContacts();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(result);
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return me.objectyan.screensharing.protobuf.CarlifeContactsProto.CarlifeContacts.getDescriptor();
      }

      public me.objectyan.screensharing.protobuf.CarlifeContactsProto.CarlifeContacts getDefaultInstanceForType() {
        return me.objectyan.screensharing.protobuf.CarlifeContactsProto.CarlifeContacts.getDefaultInstance();
      }

      public boolean isInitialized() {
        return result.isInitialized();
      }
      public me.objectyan.screensharing.protobuf.CarlifeContactsProto.CarlifeContacts build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }

      private me.objectyan.screensharing.protobuf.CarlifeContactsProto.CarlifeContacts buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }

      public me.objectyan.screensharing.protobuf.CarlifeContactsProto.CarlifeContacts buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        me.objectyan.screensharing.protobuf.CarlifeContactsProto.CarlifeContacts returnMe = result;
        result = null;
        return returnMe;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof me.objectyan.screensharing.protobuf.CarlifeContactsProto.CarlifeContacts) {
          return mergeFrom((me.objectyan.screensharing.protobuf.CarlifeContactsProto.CarlifeContacts)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(me.objectyan.screensharing.protobuf.CarlifeContactsProto.CarlifeContacts other) {
        if (other == me.objectyan.screensharing.protobuf.CarlifeContactsProto.CarlifeContacts.getDefaultInstance()) return this;
        if (other.hasCid()) {
          setCid(other.getCid());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasNumber()) {
          setNumber(other.getNumber());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setCid(input.readInt32());
              break;
            }
            case 18: {
              setName(input.readString());
              break;
            }
            case 26: {
              setNumber(input.readString());
              break;
            }
          }
        }
      }


      // required int32 cid = 1;
      public boolean hasCid() {
        return result.hasCid();
      }
      public int getCid() {
        return result.getCid();
      }
      public Builder setCid(int value) {
        result.hasCid = true;
        result.cid_ = value;
        return this;
      }
      public Builder clearCid() {
        result.hasCid = false;
        result.cid_ = 0;
        return this;
      }

      // required string name = 2;
      public boolean hasName() {
        return result.hasName();
      }
      public String getName() {
        return result.getName();
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasName = true;
        result.name_ = value;
        return this;
      }
      public Builder clearName() {
        result.hasName = false;
        result.name_ = getDefaultInstance().getName();
        return this;
      }

      // required string number = 3;
      public boolean hasNumber() {
        return result.hasNumber();
      }
      public String getNumber() {
        return result.getNumber();
      }
      public Builder setNumber(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasNumber = true;
        result.number_ = value;
        return this;
      }
      public Builder clearNumber() {
        result.hasNumber = false;
        result.number_ = getDefaultInstance().getNumber();
        return this;
      }
    }

    static {
      me.objectyan.screensharing.protobuf.CarlifeContactsProto.getDescriptor();
    }

    static {
      me.objectyan.screensharing.protobuf.CarlifeContactsProto.internalForceInit();
    }
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_baidu_carlife_protobuf_CarlifeContacts_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_baidu_carlife_protobuf_CarlifeContacts_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\032CarlifeContactsProto.proto\022\032com.baidu." +
      "carlife.protobuf\"<\n\017CarlifeContacts\022\013\n\003c" +
      "id\030\001 \002(\005\022\014\n\004name\030\002 \002(\t\022\016\n\006number\030\003 \002(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_baidu_carlife_protobuf_CarlifeContacts_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_baidu_carlife_protobuf_CarlifeContacts_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_baidu_carlife_protobuf_CarlifeContacts_descriptor,
              new String[] { "Cid", "Name", "Number", },
              me.objectyan.screensharing.protobuf.CarlifeContactsProto.CarlifeContacts.class,
              me.objectyan.screensharing.protobuf.CarlifeContactsProto.CarlifeContacts.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
}
