// Generated by the protocol buffer compiler.  DO NOT EDIT!

package me.objectyan.screensharing.protobuf;

public final class CarlifeFeatureConfigListProto {
  private CarlifeFeatureConfigListProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class CarlifeFeatureConfigList extends
      com.google.protobuf.GeneratedMessage {
    // Use CarlifeFeatureConfigList.newBuilder() to construct.
    private CarlifeFeatureConfigList() {}
    
    private static final CarlifeFeatureConfigList defaultInstance = new CarlifeFeatureConfigList();
    public static CarlifeFeatureConfigList getDefaultInstance() {
      return defaultInstance;
    }
    
    public CarlifeFeatureConfigList getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return me.objectyan.screensharing.protobuf.CarlifeFeatureConfigListProto.internal_static_com_baidu_carlife_protobuf_CarlifeFeatureConfigList_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return me.objectyan.screensharing.protobuf.CarlifeFeatureConfigListProto.internal_static_com_baidu_carlife_protobuf_CarlifeFeatureConfigList_fieldAccessorTable;
    }
    
    // required int32 cnt = 1;
    public static final int CNT_FIELD_NUMBER = 1;
    private boolean hasCnt;
    private int cnt_ = 0;
    public boolean hasCnt() { return hasCnt; }
    public int getCnt() { return cnt_; }
    
    // repeated .me.objectyan.screensharing.protobuf.CarlifeFeatureConfig featureConfig = 2;
    public static final int FEATURECONFIG_FIELD_NUMBER = 2;
    private java.util.List<me.objectyan.screensharing.protobuf.CarlifeFeatureConfigProto.CarlifeFeatureConfig> featureConfig_ =
      java.util.Collections.emptyList();
    public java.util.List<me.objectyan.screensharing.protobuf.CarlifeFeatureConfigProto.CarlifeFeatureConfig> getFeatureConfigList() {
      return featureConfig_;
    }
    public int getFeatureConfigCount() { return featureConfig_.size(); }
    public me.objectyan.screensharing.protobuf.CarlifeFeatureConfigProto.CarlifeFeatureConfig getFeatureConfig(int index) {
      return featureConfig_.get(index);
    }
    
    public final boolean isInitialized() {
      if (!hasCnt) return false;
      for (me.objectyan.screensharing.protobuf.CarlifeFeatureConfigProto.CarlifeFeatureConfig element : getFeatureConfigList()) {
        if (!element.isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasCnt()) {
        output.writeInt32(1, getCnt());
      }
      for (me.objectyan.screensharing.protobuf.CarlifeFeatureConfigProto.CarlifeFeatureConfig element : getFeatureConfigList()) {
        output.writeMessage(2, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasCnt()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getCnt());
      }
      for (me.objectyan.screensharing.protobuf.CarlifeFeatureConfigProto.CarlifeFeatureConfig element : getFeatureConfigList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, element);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static me.objectyan.screensharing.protobuf.CarlifeFeatureConfigListProto.CarlifeFeatureConfigList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static me.objectyan.screensharing.protobuf.CarlifeFeatureConfigListProto.CarlifeFeatureConfigList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static me.objectyan.screensharing.protobuf.CarlifeFeatureConfigListProto.CarlifeFeatureConfigList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static me.objectyan.screensharing.protobuf.CarlifeFeatureConfigListProto.CarlifeFeatureConfigList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static me.objectyan.screensharing.protobuf.CarlifeFeatureConfigListProto.CarlifeFeatureConfigList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static me.objectyan.screensharing.protobuf.CarlifeFeatureConfigListProto.CarlifeFeatureConfigList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static me.objectyan.screensharing.protobuf.CarlifeFeatureConfigListProto.CarlifeFeatureConfigList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static me.objectyan.screensharing.protobuf.CarlifeFeatureConfigListProto.CarlifeFeatureConfigList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static me.objectyan.screensharing.protobuf.CarlifeFeatureConfigListProto.CarlifeFeatureConfigList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static me.objectyan.screensharing.protobuf.CarlifeFeatureConfigListProto.CarlifeFeatureConfigList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(me.objectyan.screensharing.protobuf.CarlifeFeatureConfigListProto.CarlifeFeatureConfigList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private me.objectyan.screensharing.protobuf.CarlifeFeatureConfigListProto.CarlifeFeatureConfigList result;
      
      // Construct using me.objectyan.screensharing.protobuf.CarlifeFeatureConfigListProto.CarlifeFeatureConfigList.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new me.objectyan.screensharing.protobuf.CarlifeFeatureConfigListProto.CarlifeFeatureConfigList();
        return builder;
      }
      
      protected me.objectyan.screensharing.protobuf.CarlifeFeatureConfigListProto.CarlifeFeatureConfigList internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new me.objectyan.screensharing.protobuf.CarlifeFeatureConfigListProto.CarlifeFeatureConfigList();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return me.objectyan.screensharing.protobuf.CarlifeFeatureConfigListProto.CarlifeFeatureConfigList.getDescriptor();
      }
      
      public me.objectyan.screensharing.protobuf.CarlifeFeatureConfigListProto.CarlifeFeatureConfigList getDefaultInstanceForType() {
        return me.objectyan.screensharing.protobuf.CarlifeFeatureConfigListProto.CarlifeFeatureConfigList.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public me.objectyan.screensharing.protobuf.CarlifeFeatureConfigListProto.CarlifeFeatureConfigList build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private me.objectyan.screensharing.protobuf.CarlifeFeatureConfigListProto.CarlifeFeatureConfigList buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public me.objectyan.screensharing.protobuf.CarlifeFeatureConfigListProto.CarlifeFeatureConfigList buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.featureConfig_ != java.util.Collections.EMPTY_LIST) {
          result.featureConfig_ =
            java.util.Collections.unmodifiableList(result.featureConfig_);
        }
        me.objectyan.screensharing.protobuf.CarlifeFeatureConfigListProto.CarlifeFeatureConfigList returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof me.objectyan.screensharing.protobuf.CarlifeFeatureConfigListProto.CarlifeFeatureConfigList) {
          return mergeFrom((me.objectyan.screensharing.protobuf.CarlifeFeatureConfigListProto.CarlifeFeatureConfigList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(me.objectyan.screensharing.protobuf.CarlifeFeatureConfigListProto.CarlifeFeatureConfigList other) {
        if (other == me.objectyan.screensharing.protobuf.CarlifeFeatureConfigListProto.CarlifeFeatureConfigList.getDefaultInstance()) return this;
        if (other.hasCnt()) {
          setCnt(other.getCnt());
        }
        if (!other.featureConfig_.isEmpty()) {
          if (result.featureConfig_.isEmpty()) {
            result.featureConfig_ = new java.util.ArrayList<me.objectyan.screensharing.protobuf.CarlifeFeatureConfigProto.CarlifeFeatureConfig>();
          }
          result.featureConfig_.addAll(other.featureConfig_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setCnt(input.readInt32());
              break;
            }
            case 18: {
              me.objectyan.screensharing.protobuf.CarlifeFeatureConfigProto.CarlifeFeatureConfig.Builder subBuilder = me.objectyan.screensharing.protobuf.CarlifeFeatureConfigProto.CarlifeFeatureConfig.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addFeatureConfig(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // required int32 cnt = 1;
      public boolean hasCnt() {
        return result.hasCnt();
      }
      public int getCnt() {
        return result.getCnt();
      }
      public Builder setCnt(int value) {
        result.hasCnt = true;
        result.cnt_ = value;
        return this;
      }
      public Builder clearCnt() {
        result.hasCnt = false;
        result.cnt_ = 0;
        return this;
      }
      
      // repeated .me.objectyan.screensharing.protobuf.CarlifeFeatureConfig featureConfig = 2;
      public java.util.List<me.objectyan.screensharing.protobuf.CarlifeFeatureConfigProto.CarlifeFeatureConfig> getFeatureConfigList() {
        return java.util.Collections.unmodifiableList(result.featureConfig_);
      }
      public int getFeatureConfigCount() {
        return result.getFeatureConfigCount();
      }
      public me.objectyan.screensharing.protobuf.CarlifeFeatureConfigProto.CarlifeFeatureConfig getFeatureConfig(int index) {
        return result.getFeatureConfig(index);
      }
      public Builder setFeatureConfig(int index, me.objectyan.screensharing.protobuf.CarlifeFeatureConfigProto.CarlifeFeatureConfig value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.featureConfig_.set(index, value);
        return this;
      }
      public Builder setFeatureConfig(int index, me.objectyan.screensharing.protobuf.CarlifeFeatureConfigProto.CarlifeFeatureConfig.Builder builderForValue) {
        result.featureConfig_.set(index, builderForValue.build());
        return this;
      }
      public Builder addFeatureConfig(me.objectyan.screensharing.protobuf.CarlifeFeatureConfigProto.CarlifeFeatureConfig value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.featureConfig_.isEmpty()) {
          result.featureConfig_ = new java.util.ArrayList<me.objectyan.screensharing.protobuf.CarlifeFeatureConfigProto.CarlifeFeatureConfig>();
        }
        result.featureConfig_.add(value);
        return this;
      }
      public Builder addFeatureConfig(me.objectyan.screensharing.protobuf.CarlifeFeatureConfigProto.CarlifeFeatureConfig.Builder builderForValue) {
        if (result.featureConfig_.isEmpty()) {
          result.featureConfig_ = new java.util.ArrayList<me.objectyan.screensharing.protobuf.CarlifeFeatureConfigProto.CarlifeFeatureConfig>();
        }
        result.featureConfig_.add(builderForValue.build());
        return this;
      }
      public Builder addAllFeatureConfig(
          Iterable<? extends me.objectyan.screensharing.protobuf.CarlifeFeatureConfigProto.CarlifeFeatureConfig> values) {
        if (result.featureConfig_.isEmpty()) {
          result.featureConfig_ = new java.util.ArrayList<me.objectyan.screensharing.protobuf.CarlifeFeatureConfigProto.CarlifeFeatureConfig>();
        }
        super.addAll(values, result.featureConfig_);
        return this;
      }
      public Builder clearFeatureConfig() {
        result.featureConfig_ = java.util.Collections.emptyList();
        return this;
      }
    }

    static {
      me.objectyan.screensharing.protobuf.CarlifeFeatureConfigListProto.getDescriptor();
    }

    static {
      me.objectyan.screensharing.protobuf.CarlifeFeatureConfigListProto.internalForceInit();
    }
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_baidu_carlife_protobuf_CarlifeFeatureConfigList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_baidu_carlife_protobuf_CarlifeFeatureConfigList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n#CarlifeFeatureConfigListProto.proto\022\032c" +
      "om.baidu.carlife.protobuf\032\037CarlifeFeatur" +
      "eConfigProto.proto\"p\n\030CarlifeFeatureConf" +
      "igList\022\013\n\003cnt\030\001 \002(\005\022G\n\rfeatureConfig\030\002 \003" +
      "(\01320.me.objectyan.screensharing.protobuf.CarlifeF" +
      "eatureConfig"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_baidu_carlife_protobuf_CarlifeFeatureConfigList_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_baidu_carlife_protobuf_CarlifeFeatureConfigList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_baidu_carlife_protobuf_CarlifeFeatureConfigList_descriptor,
              new String[] { "Cnt", "FeatureConfig", },
              me.objectyan.screensharing.protobuf.CarlifeFeatureConfigListProto.CarlifeFeatureConfigList.class,
              me.objectyan.screensharing.protobuf.CarlifeFeatureConfigListProto.CarlifeFeatureConfigList.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          me.objectyan.screensharing.protobuf.CarlifeFeatureConfigProto.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
}
